FROM golang:1.24.4-alpine AS builder
WORKDIR /src

COPY go.mod ./
COPY cmd ./cmd
COPY internal ./internal

RUN CGO_ENABLED=0 GOOS=linux go build -o /out/restaurant-service ./cmd/restaurant-service

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /out/restaurant-service /app/restaurant-service
EXPOSE 8081
ENTRYPOINT ["/app/restaurant-service"]
